<?php
/**
 * Title: Metabox
 *
 * Description: Defines metabox fields for page.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

add_action('admin_head', 'cyberchimps_load_meta_boxes_scripts');
function cyberchimps_load_meta_boxes_scripts() {
	global $post_type;

	// Set library path.
	$lib_path = get_template_directory_uri() . "/cyberchimps/lib/";
	
	if ( $post_type == 'page' ) :
		wp_enqueue_style( 'meta-boxes-css', $lib_path . 'css/metabox-tabs.css' );
	
		// Enqueue only if it is not done before
		if( !wp_script_is('jf-metabox-tabs') ) :
			wp_enqueue_script('meta-boxes-js', $lib_path . 'js/metabox-tabs.js', array('jquery'));	
		endif;	
	endif;
}

add_action('init', 'cyberchimps_init_meta_boxes');
function cyberchimps_init_meta_boxes() {
	
	// Set image path
	$directory_uri	 = get_template_directory_uri();
	$image_path		 = $directory_uri . "/cyberchimps/lib/images/";
	$slider_image	 = $directory_uri . "/elements/lib/images/slider/slide1.jpg";
	
	// Declare variables
	$carousel_options = array();
	$slider_options = array();
	$boxes_options = array();
	$blog_options = array();
	
	// Call taxonomies for select options
	
	$carousel_terms = get_terms('carousel_categories', 'hide_empty=0');
	if( ! is_wp_error( $carousel_terms ) ): 
		foreach($carousel_terms as $term) {
			$carousel_options[$term->slug] = $term->name;
		}
	endif;
	
	$slide_terms = get_terms('slide_categories', 'hide_empty=0');
	if( ! is_wp_error( $slide_terms ) ):
		foreach($slide_terms as $term) {
			$slider_options[$term->slug] = $term->name;
		}
	endif;
	
	// Get custom categories of boxes element
	$boxes_terms = get_terms('boxes_categories', 'hide_empty=0');
	if( ! is_wp_error( $boxes_terms ) ):
		foreach($boxes_terms as $term) {
			$boxes_options[$term->slug] = $term->name;
		}
	endif;
	
	$category_terms = get_terms('category', 'hide_empty=0');
	if( ! is_wp_error( $category_terms ) ):
		$blog_options['all'] = "All";
		foreach($category_terms as $term) {
			$blog_options[$term->slug] = $term->name;
		}
	endif;
	
	// Get all post categories
	$all_cats = array();
	$all_categories = get_terms( 'category');
	if( ! is_wp_error( $all_categories ) ) {
		foreach( $all_categories as $all_cat ) {
			$all_cats[$all_cat->term_id] = $all_cat->name;
		}
	}
	// End taxonomy call
	
	$meta_boxes = array();

	$mb = new Chimps_Metabox('pages', 'Page Options', array('pages' => array('page')));
	$mb
		->tab("Page Options")
			->image_select('cyberchimps_page_sidebar', __( 'Select Page Layout', 'cyberchimps' ), '',
				array('options' => apply_filters( 'sidebar_layout_options', array(
																					'full_width' => $image_path . '1col.png',
																					'right_sidebar' => $image_path . '2cr.png',
																					'left_sidebar' => $image_path . '2cl.png',
																					'left_right_sidebar' => $image_path . '3cr.png',
																					'content_middle' => $image_path . '3col.png'
																				) ), 'std' => 'right_sidebar') )
			->checkbox('cyberchimps_page_title_toggle', __('Page Title', 'cyberchimps'), '', array('std' => '1'))
			->section_order('cyberchimps_page_section_order', __( 'Page Elements', 'cyberchimps' ), '', array(					
				'options' => apply_filters( 'cyberchimps_elements_draganddrop_page_options', array(
					'boxes'				 => __( 'Boxes', 'cyberchimps' ),					
					'page_section'		 => __( 'Page', 'cyberchimps' ),
					'slider_lite'		 => __( 'Slider Lite', 'cyberchimps' ),
					'twitterbar_section' => __( 'Twitter Bar', 'cyberchimps' )
				) ),
					'std' => array( 'page_section' )
				))
			->pagehelp('', __( 'Need Help?', 'cyberchimps' ), '')
		->tab("Slider Options")
			->select('cyberchimps_slider_lite_size', __( 'Slider Size', 'cyberchimps' ), '', array( 'options' => array('full' => __( 'Full', 'cyberchimps' ), 'half' => __( 'Half', 'cyberchimps' )) ) )
			->text('cyberchimps_slider_lite_height', __( 'Slider Height', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_speed', __( 'Slider Speed', 'cyberchimps' ), '', array( 'std' => 3000 ) )
			->checkbox('cyberchimps_slider_lite_arrows', __( 'Slider Arrows', 'cyberchimps' ), '', array('std' => '1') )
			->single_image('cyberchimps_slider_lite_slide_image_1', __( 'Slide Image 1', 'cyberchimps' ), '', array('std' => $slider_image ))
			->text('cyberchimps_slider_lite_slide_url_1', __( 'Slide Link 1', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_1', __( 'Slide Caption 1', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_2', __( 'Slide Image 2', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_2', __( 'Slide Link 2', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_2', __( 'Slide Caption 2', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_3', __( 'Slide Image 3', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_3', __( 'Slide Link 3', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_3', __( 'Slide Caption 3', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_4', __( 'Slide Image 4', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_4', __( 'Slide Link 4', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_4', __( 'Slide Caption 4', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_5', __( 'Slide Image 5', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_5', __( 'Slide Link 5', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_5', __( 'Slide Caption 5', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_6', __( 'Slide Image 6', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_6', __( 'Slide Link 6', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_6', __( 'Slide Caption 6', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_7', __( 'Slide Image 7', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_7', __( 'Slide Link 7', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_7', __( 'Slide Caption 7', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_8', __( 'Slide Image 8', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_8', __( 'Slide Link 8', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_8', __( 'Slide Caption 8', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_9', __( 'Slide Image 9', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_9', __( 'Slide Link 9', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_9', __( 'Slide Caption 9', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_10', __( 'Slide Image 10', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_10', __( 'Slide Link 10', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_10', __( 'Slide Caption 10', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_11', __( 'Slide Image 11', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_11', __( 'Slide Link 11', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_caption_11', __( 'Slide Caption 11', 'cyberchimps' ), '' )
			->single_image('cyberchimps_slider_lite_slide_image_12', __( 'Slide Image 12', 'cyberchimps' ), '' )
			->text('cyberchimps_slider_lite_slide_url_12', __( 'Slide Link 12', 'cyberchimps' ), '' )		
			->text('cyberchimps_slider_lite_slide_caption_12', __( 'Slide Caption 12', 'cyberchimps' ), '' )
		->tab( "Product Options" )
			->select( 'cyberchimps_product_layout', __( 'Product Layout', 'cyberchimps' ), '',
				array( 'options' => array( '1' => 'Text Left - Media Right', '2' => 'Text Right - Media Left' ) ) )
			->text( 'cyberchimps_product_title', __( 'Product Title', 'cyberchimps' ), '', array( 'std' => __( 'Product', 'cyberchimps' ) ) )
			->textarea( 'cyberchimps_product_text', __( 'Product Text', 'cyberchimps' ), '' )
			->select( 'cyberchimps_product_media_type', __( 'Media Type', 'cyberchimps' ), '', array( 'options' => array( '1' => 'Image', '2' => 'Video' ) ) )
			->single_image( 'cyberchimps_product_image', __( 'Product Image', 'cyberchimps' ), '', array( 'std' =>  $directory_uri . '/images/branding/product.jpg' ) )
			->checkbox( 'cyberchimps_product_image_link_toggle', __( 'Product Image Link', 'cyberchimps' ), '', array( 'std' => '1' ) )
			->text( 'cyberchimps_product_image_link', __( 'Link URL', 'cyberchimps' ), '', array( 'std' => home_url() ) )
			->textarea( 'cyberchimps_product_video', __( 'Video Embed', 'cyberchimps' ), '' )
		->tab("Callout Options")
			->text('callout_title', __( 'Callout Title', 'cyberchimps' ), '',
				array('std' => sprintf( __( '%1$s\'s Call Out Element', 'cyberchimps' ),
					apply_filters( 'cyberchimps_current_theme_name', 'Cyberchimps' ) ) ) )
			->textarea('callout_text', __( 'Callout Text', 'cyberchimps' ), '',
				array('std' => sprintf( __( 'Use %1$s\'s Call Out section on any page where you want to deliver an important message to your customer or client.', 'cyberchimps' ),
					apply_filters( 'cyberchimps_current_theme_name', 'Cyberchimps' ) ) ) )
			->checkbox('disable_callout_button', __( 'Callout Button', 'cyberchimps' ), '', array('std' => '1'))
			->text('callout_button_text', __( 'Callout Button Text', 'cyberchimps' ), '')
			->text('callout_url', __( 'Callout Button URL', 'cyberchimps' ), '')
			->checkbox('extra_callout_options', __( 'Custom Callout Options', 'cyberchimps' ), '', array('std' => '0'))
			->single_image('callout_image', __( 'Custom Button Image', 'cyberchimps' ), '')
			->color('custom_callout_color', __( 'Custom Background Color', 'cyberchimps' ), '')
			->color('custom_callout_title_color', __( 'Custom Title Color', 'cyberchimps' ), '')
			->color('custom_callout_text_color', __( 'Custom Text Color', 'cyberchimps' ), '')
			->color('custom_callout_button_color', __( 'Custom Button Color', 'cyberchimps' ), '')
			->color('custom_callout_button_text_color', __( 'Custom Button Text Color', 'cyberchimps' ), '')
			->pagehelp('', __( 'Need help?', 'cyberchimps' ), '')
		->tab("HTML Box Options")
			->textarea('html_box', __( 'Custom HTML', 'cyberchimps' ), __( 'Enter your custom html here', 'cyberchimps' ) )
		->tab("Recent Posts Options")
			->checkbox('cyberchimps_recent_posts_title_toggle', __( 'Title', 'cyberchimps' ), '', array('std' => '1') )
			->text('cyberchimps_recent_posts_title', __( 'Recent Posts Title', 'cyberchimps' ), '', array('std' => __( 'Latest Blog Posts', 'cyberchimps' ) ) )
			->select('cyberchimps_recent_posts_category', __( 'Post Category', 'cyberchimps' ), '', array('options' => $blog_options, __( 'All', 'cyberchimps' ) ) )
			->checkbox('cyberchimps_recent_posts_images_toggle', __( 'Images', 'cyberchimps' ), '')
		->tab("Carousel Options")
			->select('carousel_category', __( 'Carousel Category', 'cyberchimps' ), '', array('options' => ( $carousel_options ? $carousel_options : array( 'cc_no_options' => __( 'You need to create a Category', 'cyberchimps' ) ) ) ) )
		->tab("Twitter Options")
			->text('cyberchimps_twitter_handle', __( 'Twitter Handle', 'cyberchimps' ), __( 'Enter your Twitter handle if using the Twitter bar', 'cyberchimps' ) )
		->tab("Boxes Options")
			->select('boxes_category', __( 'Boxes Category', 'cyberchimps' ), '', array('options' => ( $boxes_options ? $boxes_options : array( 'cc_no_options' => __( 'You need to create a Category', 'cyberchimps' ) ) ) ) )
		->end();

	foreach ($meta_boxes as $meta_box) {
		$my_box = new RW_Meta_Box_Taxonomy($meta_box);
	}
}