<?php
/**
 * Title: Pro features
 *
 * Description: creates options and features from pro themes.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

//add sections 2nd key is the position in that heading
function cyberchimps_add_sections( $original ) {
	$new_section[][4] = array( 
														'id' => 'cyberchimps_header_details_section',
														'label' => __('Contact Element', 'cyberchimps'),
														'heading' => 'cyberchimps_header_heading'
													);
	
	$new_sections = cyberchimps_array_section_organizer( $original, $new_section );
	
	return $new_sections;
}
add_filter( 'cyberchimps_sections_filter', 'cyberchimps_add_sections', 1 );

//add fields 2nd key is the position in that section
function cyberchimps_add_fields( $original ) {
	$new_field[][1] = array( 
													'name' => __('Details', 'cyberchimps'),
													'id' => 'contact_details',
													'std' => '',
													'type' => 'textarea',
													'section' => 'cyberchimps_header_details_section',
													'heading' => 'cyberchimps_header_heading'
												 );
	$new_field[][2] = array( 
													'name' => __('Breadcrumbs', 'cyberchimps'),
													'id' => 'single_post_breadcrumbs',
													'type' => 'toggle',
													'section' => 'cyberchimps_single_post_section',
													'heading' => 'cyberchimps_templates_heading'
													);
	$new_field[][2] = array( 
													'name' => __('Breadcrumbs', 'cyberchimps'),
													'id' => 'archive_breadcrumbs',
													'type' => 'toggle',
													'section' => 'cyberchimps_archive_section',
													'heading' => 'cyberchimps_templates_heading'
													);
																								
	$new_fields = cyberchimps_array_field_organizer( $original, $new_field );
	return $new_fields;
}
add_filter( 'cyberchimps_field_filter', 'cyberchimps_add_fields', 1 );