<?php
/**
 * Title: Header template.
 *
 * Description: Defines header content.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="ie ie6 lte9 lte8 lte7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 7]>
<html class="ie ie7 lte9 lte8 lte7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 lte9 lte8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 9]>
<html class="ie ie9" <?php language_attributes(); ?>> 
<![endif]-->
<!--[if gt IE 9]>  <html <?php language_attributes(); ?>> <![endif]-->
<!--[if !IE]><!--> 
<html <?php language_attributes(); ?>>
<!--<![endif]-->
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>" />
	<meta name="viewport" content="initial-scale=1.0; maximum-scale=3.0; width=device-width" />
	
	<title><?php wp_title(''); ?></title>
	
	<link rel="profile" href="http://gmpg.org/xfn/11" />
	<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>" />
	
	<!-- IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="<?php echo get_template_directory_uri(); ?>/inc/js/html5.js" type="text/javascript"></script>
	<![endif]-->
	
	<?php wp_head(); ?>

</head>

<body <?php body_class(); ?>>

<div class="full-width-container header-full-width">

	<?php $get_header_image = cyberchimps_get_option( 'header_image' );
        $default_image = apply_filters( 'header_image', get_template_directory_uri() . '/images/header.jpg' );
        $header_image = ( $get_header_image != false && $get_header_image != '' ) ? $get_header_image : $default_image; 
  ?>
	<img class="header-image" src="<?php echo $header_image; ?>" alt="Image" />
	<div class="header-image-banner"></div><!-- banner -->

  <div class="header-container">
  
    <div class="container">
      
    <?php do_action('cyberchimps_before_wrapper'); ?>
    
      <div class="container-fluid">
      
        <div id="header_nav_container">
        
          <div class="row-fluid">
          
            <div class="span4">
            <?php cyberchimps_header_logo(); ?>
            </div><!-- span4 -->
            <div class="span8">
            <?php do_action('cyberchimps_before_navigation'); ?>
            

              
            <?php do_action('cyberchimps_after_navigation'); ?>
            </div><!-- span8 -->
          </div><!-- row fluid -->
        </div><!-- header nav container -->
        
      </div><!-- container-fluid -->
    </div><!-- container -->
  </div><!-- header container -->
</div><!--container full width -->
<div class="container">
<div id="wrapper" class="container-fluid">