<?php
/**
 * Title: Product Elements
 *
 * Description: Defines actions for product element and it's markup.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
**/

// Don't load directly
if ( !defined('ABSPATH') ) { die('-1'); }

add_action( 'product', 'cyberchimps_product_element_render_display' );

function cyberchimps_product_element_render_display(){
	global $options, $post;

	if ( is_page() ) {
	
		// Get page options
		$layout			= get_post_meta($post->ID, 'cyberchimps_product_layout' , true);
		$title			= get_post_meta($post->ID, 'cyberchimps_product_title' , true);
		$text			= get_post_meta($post->ID, 'cyberchimps_product_text' , true);
		$media_type		= get_post_meta($post->ID, 'cyberchimps_product_media_type' , true);
		$image			= get_post_meta($post->ID, 'cyberchimps_product_image' , true);
		$link_toggle	= get_post_meta($post->ID, 'cyberchimps_product_image_link_toggle' , true);
		$link			= get_post_meta($post->ID, 'cyberchimps_product_image_link' , true);
		$video			= get_post_meta($post->ID, 'cyberchimps_product_video' , true);
	}
	else {
	
		// Get blog options
		$layout			= cyberchimps_get_option( 'cyberchimps_product_layout' );
		$title			= cyberchimps_get_option( 'cyberchimps_product_title' );
		$text			= cyberchimps_get_option( 'cyberchimps_product_text' );
		$media_type		= cyberchimps_get_option( 'cyberchimps_product_media_type' );
		$image			= cyberchimps_get_option( 'cyberchimps_product_image' );
		$link_toggle	= cyberchimps_get_option( 'cyberchimps_product_image_link_toggle' );
		$link			= cyberchimps_get_option( 'cyberchimps_product_image_link' );
		$video			= cyberchimps_get_option( 'cyberchimps_product_video' );
	}
	
	// Prepare media : Check if image or video is selected
	if ( $media_type == "1" ) {

		// Check if image link is on and the link is supplied.
		if( $link_toggle == "1" && $link != "" ) {
			$media = "<a href='$link'><img src='$image' /></a>";
		}
		else {
			$media = "<img src='$image'>";
		}
	}
	else {
		$media ="<div class='flex-video'>$video</div>";
	}
	
	// Get layout (position of text and media)
	if ( $layout == "1" ) {
	
		// Text Left - Media Right
		$output = "
			<div id='product-text' class='span6'>
				<h2>$title</h2>
				<p>$text </p>
			</div>
			<div id='product-media' class='span6'>
				$media
			</div>"; 
	}
	else {
	
		// Text Right - Media Left
		$output = "
			<div id='product-media' class='span6'>
				$media
			</div>
			<div id='product-text' class='span6'>
				<h2>$title</h2>
				<p>$text </p>
			</div>"; 
	}
	?>

	<div id="product-container" class="row-fluid">
  	<div class="product-sub-container">
			<?php echo $output; ?>
    </div>
	</div>

<?php
}

/**
* End
*/

?>